### ISSUE TITLE
OAuth login fails

### ISSUE THREAD

**Issue by ivanistheone** [recursecenter/blaggregator#142] opened 2017-05-10 05:59 UTC
When I go to https://blaggregator.recurse.com/ and I start the OAuth flow, I get sent back to
https://blaggregator.recurse.com/complete/hackerschool/?code=613.......&state=J2T.....
with the following generic Heroku error displayed in the page:

<img width="520" alt="screen shot 2017-05-10 at 1 55 23 am" src="https://cloud.githubusercontent.com/assets/163966/25884976/e37c7f20-3523-11e7-9143-04af897d9af1.png">

Please check the logs between 1:45am EDT and 1:57EDT on May 10th.

**Comment by strugee** [comment] 2017-05-13 06:07
I can still reproduce; pinging @sursh, @punchagan who I assume have access to the Heroku application

**Comment by punchagan** [comment] 2017-05-15 03:37
Thanks for filing the issue. I was on a holiday, and unable to look into this further. I will look into what's going on, soon.

**Comment by punchagan** [comment] 2017-05-15 03:52
@davidbalbert @zachallaun Have there been any API changes for RC? 
`https://www.recurse.com/api/v1/people/me?access_token=$token` seems to be giving an error.

**Comment by nicholasbs** [comment] 2017-05-15 13:42
Thanks for the reports and sorry about this all. We deployed some API updates late last week, which I assume are the culprit. Dave and Zach will investigate as soon as they're in this morning.

**Comment by zachallaun** [comment] 2017-05-15 18:33
This is now fixed! Sorry for the trouble. We made some changes late last week to the way authentication and permissions work with our API (in anticipation of some new ways to access the API), and in doing so accidentally forbade Recursers from doing certain actions that should be allowed.

**Closed by zachallaun** 2017-05-15 18:33 UTC

**Comment by punchagan** [comment] 2017-05-16 02:55
Thanks for fixing this @zachallaun!
